blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://discord.gg/dmSFJGqeK2
    about: Please ask and answer questions here
  - name: List a token
    url: https://discord.gg/dmSFJGqeK2
    about: Any requests to add a token to Hydrogen should go in the support > builders channel
